### ISSUE TITLE
Add paging response headers to all methods with paging parameters

### ISSUE THREAD

**Issue by callsoft** [SharpsCompliance/PDSC#1]
For both accounts and accounts/accountnames, can we
go ahead and add the paging response headers—this will make things much easier to test various accounts – can log in as admin then search for the account to use, as opposed to creating individual login accounts.  CS will need this ability anyway.

```
            X-Paging-PageNo:
              schema:
                type: integer
              description: Page number of response
            X-Paging-PageSize:
              schema:
                type: integer
              description: Page size
            X-Paging-PageCount:
              schema:
                type: integer
              description: Number of pages available
            X-Paging-TotalRecordCount:
              schema:
                type: integer
              description: Total number of records available
```
