### ISSUE TITLE
Clarify /accounts/{custId}/medsafeautoships - should it be autoreorders or nonMedsafe autoships?

### ISSUE THREAD

**Issue by callsoft** [SharpsCompliance/PDSC#14]
Is this really MedSafe related?  Should it be nonMedSafe autoships or are these autoreorders?

`/accounts/{custId}/medsafeautoships
`
                Gives a list of items tied to the custid/custaddrid that are configured for autoship, along with frequency and last/next order date by item.  I assume this was originally for non-medsafe autoships (since that was covered by the above, right?).   I renamed this to medsafeautoships based on our last conversation about it, but I’m guessing that it should just be autoships like it was before.  I think this was originally to enable auto-reorder, so maybe it should be called autoreorder instead of autoship.  

```
MedSafeAutoShip:
      type: object
      properties:
        custId:
          type: string
        custAddrId:
          type: string
        customerName:
          type: string
        addrName:
          type: string
        itemId:
          type: string
        itemDescription:
          type: string
        frequency:
          type: string
        lastOrderDate:
          type: string
          format: date
        nextOrderDate:
          type: string
          format: date

```
