### ISSUE TITLE
Implement /accounts/{custId}/medsafeautoshipstatus

### ISSUE THREAD

**Issue by callsoft** [SharpsCompliance/PDSC#15]
Implement` /accounts/{custId}/medsafeautoshipstatus`

Returns single object: 

   ```
 MedSafeAutoShipStatus:
      type: object
      properties:
        custId:
          type: string
        custAddrId:
          type: string
        linerFrequency:
          type: string
          format: date
        nextOrderDate:
          type: string
          format: date
        lastOrderDate:
          type: string
          format: date

```
