### ISSUE TITLE
Implement /invoices/{invoiceNumber}/applypayment and /invoice/applypayment

### ISSUE THREAD

**Issue by callsoft** [SharpsCompliance/PDSC#17]
Implement `POST /invoices/applypayment`

Takes an array of `ApplyPaymentRequest` and returns `200 OK` if applied successfully or `400 Bad Request` with details as to why the payment couldn't be applied.

```
    ApplyPaymentRequest:
      type: object
      required:
        - paymentAmount
        - invoiceNumber
        - paymentTransId
      properties:
        paymentAmount:
          type: number
          format: float
          example: 345.34
          readOnly: false
        invoiceNumber:
          type: string
          example: 0000109275
          readOnly: false
        paymentTransId:
          type: string
          example: 00320230230230
          description: Authorize.net transaction Id of successful payment
          readOnly: true
```
