### ISSUE TITLE
Implement /medsafeautoshipments

### ISSUE THREAD

**Issue by callsoft** [SharpsCompliance/PDSC#18]
Implement `/medsafeautoshipments` for displaying MedSafe auto shipments on the interactive MedSafe calendar in the UI.

Returns array of `MedSafeAutoShipment`

```
    MedSafeAutoShipment:
      type: object
      properties:
        custId:
          type: string
        custAddrId:
          type: string
        autoShipId:
          type: string
        autoShipDate:
          type: string
          format: date
        status:
          type: string
          enum: [SHIPPED, ONEOFF, SCHEDULED, OPENORDER]
        autoShipResultText:
          type: string
          description: Full customer facing description of autoship status.  May include auto ship details, weight, etc, items, count, or any other details that may be desired.  This text will be displayed when customer selects the corresponding date on the interactive calendar.

```
